In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
# 2 dimensional list of list
my_matrix = [[1,2,4], [2,3,4], [3,2,1]]

In [6]:
my_matrix


[[1, 2, 4], [2, 3, 4], [3, 2, 1]]

In [7]:
arr = np.array(my_matrix)

In [8]:
arr

array([[1, 2, 4],
       [2, 3, 4],
       [3, 2, 1]])

In [9]:
# use numpy built in numpy methods

In [10]:
# create array, pass start and stop
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Add step side, it will jump
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# generate arrays of all zeros
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# array of just one
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# linspace: return evenly space number with some interval
 np.linspace(2,3,1)

array([2.])

In [18]:
np.linspace(0,6,10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [19]:
np.linspace(0,6,2)

array([0., 6.])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
# Create identity matrix using Numpy
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# Identity is useful for linear algebra problem
# Its is a 2 dimensional and sqaure matrix

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
# Randomly create array
np.random.rand(2,2)

array([[0.60103251, 0.68094166],
       [0.19228381, 0.99436679]])

In [25]:
# return standard normal distribution
np.random.randn(3)

array([-0.04784259, -0.78355163,  0.96283921])

In [26]:
# for two dimensions
np.random.randn(3,3)

array([[ 0.51326212, -0.37721437, -0.31056683],
       [ 0.57688409, -1.2830271 ,  0.95118208],
       [ 1.18870517, -1.77743614, -1.40242003]])

In [27]:
np.random.randint(0,10, 100)

array([4, 5, 4, 3, 6, 9, 6, 1, 2, 4, 0, 3, 3, 2, 3, 2, 0, 9, 3, 7, 0, 8,
       9, 5, 1, 9, 7, 5, 5, 3, 8, 2, 1, 4, 9, 4, 8, 7, 6, 3, 4, 5, 5, 1,
       0, 7, 9, 3, 6, 2, 4, 2, 0, 2, 0, 5, 9, 7, 4, 5, 3, 9, 7, 4, 3, 5,
       5, 8, 5, 7, 0, 3, 5, 0, 3, 4, 7, 6, 0, 5, 3, 6, 2, 5, 6, 7, 6, 4,
       4, 3, 1, 6, 4, 8, 2, 3, 3, 6, 6, 9])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,10,2)

In [31]:
ranarr

array([2, 1])

In [32]:
# reshape method, same data of new shape

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr

array([2, 1])

In [36]:
ranarr.max()

2

In [37]:
ranarr.min()

1

In [38]:
ranarr.sum()

3

In [39]:
# find the location of max and min value
ranarr.argmax()

0

In [40]:
ranarr.argmin()

1

In [41]:
# Numpy array indexing

In [42]:
# Create sample array


In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
# pick element using indexing

In [46]:
arr[1]

1

In [47]:
arr[3]

3

In [50]:
arr[2:5]

array([2, 3, 4])

In [51]:
arr[2:4]

array([2, 3])

In [52]:
arr[:5]

array([0, 1, 2, 3, 4])

In [53]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
# numpy ability is different because of their ability to broadcast

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
slice_arr = arr[0:6]

In [58]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
slice_arr[:]

array([0, 1, 2, 3, 4, 5])

In [61]:
slice_arr[:] = 99

In [62]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [63]:
# change is also array in originla array because of memory
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_copy = arr.copy()

In [65]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy[:] = 100

In [68]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
# Indexing in 2 d array

In [73]:
arr_2d = np.array([[1,2,3], [3,2,1], [4,5,6]])

In [75]:
arr_2d

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6]])

In [76]:
# row cloumn
arr_2d[0][1]

2

In [77]:
arr_2d[0]

array([1, 2, 3])

In [81]:
arr_2d[1]

array([3, 2, 1])

In [82]:
arr_2d[2,1]

5

In [83]:
arr_2d[:1,1:]

array([[2, 3]])

In [84]:
# Conditional selection

In [85]:
arr = np.arange(1,11)

In [86]:
# Get array of boolean value
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[arr<3]

array([1, 2])

In [89]:
arr_2d = np.arange(50).reshape(5,10)

In [90]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [93]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [94]:
# Numpy operations

In [95]:
"""
Array with array
Array with scalars
Universal array functions
"""

'\nArray with array\nArray with scalars\nUniversal array functions\n'

In [96]:
arr = np.arange(0,11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [100]:
# Scalar: single member

In [101]:
# add hundrer to every element
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [102]:
# multiply hundrer to every element
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [103]:
arr / arr

/home/amber/Desktop/Amber_Gautam/datascience/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [104]:
1/arr

/home/amber/Desktop/Amber_Gautam/datascience/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [105]:
# array with exponents

In [106]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [107]:
# Universal array functions

In [110]:
# square root of every thing in array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [112]:
arr.max()

10

In [113]:
arr.min()

0

In [114]:
np.log(arr)

/home/amber/Desktop/Amber_Gautam/datascience/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [115]:
# Numpy universal function list:
# https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [116]:
# Numpy exercise:

In [119]:
# 1. Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
# Create an array of 10 one
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [123]:
# create an array of 10 5's
np.ones(10) * 5
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [125]:
# Create an array of integer 10 to 50
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [127]:
# create and event integer from 10 to 50
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [129]:
# create a 3 * 3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
# create a 3 x 3 indetity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [136]:
# generate random value between 0 to 1
np.random.rand(1)

array([0.76604246])

In [139]:
# Generate 25 random number sample for a standard normal distribution
np.random.randn(25)

array([-1.01049368, -0.27239896,  0.36898392, -0.99693575,  0.00190579,
       -0.69850256, -0.81852936,  0.38882525, -1.20551051,  0.90870357,
       -1.0806167 ,  0.26583564, -0.06920436, -0.19447093, -0.1570623 ,
       -1.25570827,  0.58687522, -0.50441263, -1.33313059,  0.72197417,
        0.21736551,  0.98809811, -0.63384042,  0.43195004,  0.27092756])

In [144]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [148]:
np.linspace(0.1,1, 100).reshape(10,10)

array([[0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
        0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818],
       [0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
        0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727],
       [0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
        0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636],
       [0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
        0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545],
       [0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
        0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455],
       [0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
        0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364],
       [0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
        0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273],
       [0.73636364, 0.74545455, 0.7545454

In [154]:
# Create an array of 20 linearly spaces points between 0 and 1
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [155]:
# Numpy indexing and solution exercise
mat = np.arange(1,26).reshape(5,5)

In [157]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [158]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [161]:
# Get sum of all values
np.sum(mat)

325

In [163]:
# standard deviation
np.std(arr)

3.1622776601683795

In [ ]:
# get sum of all 