In [3]:
# Import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
"""
Categorical value: string values
Non categorical value: numrical value column
Exercise:
1. Import libraries
2. Import dataset
3. Take care of missing data
4. Encoding the independent variable
5. Encoding the dependent variable
6. Splitting the dataset into training set and test set
7. Featue scaling: sacle all feature to make sure they are on right scale
"""

'\nCategorical value: string values\nNon categorical value: numrical value column\nExercise:\n1. Import libraries\n2. Import dataset\n3. Take care of missing data\n4. Encoding the independent variable\n5. Encoding the dependent variable\n6. Splitting the dataset into training set and test set\n7. Featue scaling: sacle all feature to make sure they are on right scale\n'

In [6]:
# Import Dataset

In [7]:
dataset = pd.read_csv('Data.csv')

In [8]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [10]:
# In machine learning there are feature and dependent variable vector
# Dependent variable are those which need to predict and feature variable are those by which we will predict
# Containg some variable with which we predict

In [11]:
"""
x: feature
y: dependent
"""

'\nx: feature\ny: dependent\n'

In [74]:
# iloc, locate indexes
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [75]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [76]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [77]:
# Taking care of missing data

In [78]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [79]:
# Handle Nan
# Ignore and delete the values if data low
# else handle missing data

In [80]:
from sklearn.impute import SimpleImputer

In [81]:
# replace with average, median or most frequently value
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [82]:
imputer

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [83]:
# fit method connect missing value with original values

In [84]:
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])


In [85]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [86]:
# encoding categorical data
"""
1. Turn category into number to
2. Convert country into number
3. For making relation
4. Encode three countries into 0 ,1 ,2 (3 different categories)
5. Create vector
6. One hot encoding
7. Mainly encode into 0's 1's and 2's country column
8. Called one hot encoding
"""

"\n1. Turn category into number to\n2. Convert country into number\n3. For making relation\n4. Encode three countries into 0 ,1 ,2 (3 different categories)\n5. Create vector\n6. One hot encoding\n7. Mainly encode into 0's 1's and 2's country column\n8. Called one hot encoding\n"

In [87]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder="passthrough")
x = np.array(ct.fit_transform(x))

In [88]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [89]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [90]:
# Encode the dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [91]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [92]:
"""
Splitting the dataset into test and training model
"""
# Most frequently question:
# 1. Do we have apply feature scaling before splitting the dataset or after the splitting of dataset
# 2. Feature scaling apply after the splitting the dataset into test and training.

'\nSplitting the dataset into test and training model\n'

In [93]:
from sklearn.model_selection import train_test_split
# create 4 seperate set
# 1. X train: matrix of feature of training set
# 2. X test: matrix of feature of test set
# 3. Y train: matrix of independent variable of train set 
# 4. Y Test: matrix of independent variable of test set
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 1)
x_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [94]:
# Feature scaling is ensuaring all the variable take values in one scale
# Why apply feature  scaling after splitting data because test set is not working later
# prevent information leakage

In [95]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [96]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [97]:
y_test

array([0, 1])

In [98]:
# Feature scaling: dominated feature not consideredby machine learning modek

In [99]:
# apply feature on some of models

In [100]:
#Feature Scaling is a technique to standardize the independent features present in the data in a fixed range. It is performed during the data pre-processing to handle highly varying magnitudes or values or units.
# apply on independent x on both test and trai n but in production not in test data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# fit scalar or stand. on training set only age and salary
x_train[:, 3:] = sc.fit_transform(x_train[:,3:])
# x test is input for trainign model
x_test[:, 3:] = sc.transform(x_test[:,3:])


In [101]:
x_test

array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
      dtype=object)

In [102]:
# all variable on same scale
x_train

array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
       [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
       [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
       [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
       [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
      dtype=object)