##### Support Vector Regression
1. We are minimizing the error
2. How SVR works: Instead of regression line it has a tube. this tube is called epsilon insensitive tube. Not care about any error inside the tube
3. Here we dont care about the error inside tube
4. It give buffer to our model.
5. Outside the tube we do care about the error.
6. Distance between tube boundary and outside error called slack variables.
7. Outside the tube are support vectors, the are dictating how tube is create, they are supporting the tube and structure.
8. Book link [www.core.ac.uk/download/pdf/81523322.pdf](Book) chapter 4
-------------------------------------------------
#### SVR Non linear
1. 3 dimension in non linear
2. Section on Kernal SVM
3. Mapping of higher dimensions
4. The kernel trick
5. Types of kernel functions
6. Non linear kernal SVR

##### Apply inverse feature scaling

In [5]:
# Import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
# Get data and apply feature scaling
dataset = pd.read_csv('Position_Salaries.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:,-1].values

In [11]:
# feature scaling in SVR
# Apply feature scaling on whole matrix x (only x_test and x_train)  
# because the values of dependent variable are in high range
# we have to apply feature scaling

In [12]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [13]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [15]:
# reshape this y in 2 d array, because standardization. in fit transform.
# Standard scalar class expect 2d array
y = y.reshape(len(y),1)

In [16]:
y

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]])

In [17]:
# feature scaling

In [21]:
#Feature Scaling is a technique to standardize the independent features present in the data in a fixed range. It is performed during the data pre-processing to handle highly varying magnitudes or values or units.
# apply on independent x on both test and trai n but in production not in test data
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
# fit scalar or stand. on training set only age and salary
x = sc_x.fit_transform(x)
y = sc_y.fit_transform(y)
# Not use standard scalar for dependent variable


In [23]:
y

array([[-0.72004253],
       [-0.70243757],
       [-0.66722767],
       [-0.59680786],
       [-0.49117815],
       [-0.35033854],
       [-0.17428902],
       [ 0.17781001],
       [ 0.88200808],
       [ 2.64250325]])

In [24]:
x

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [25]:
from sklearn.svm import SVR
# we are using radial basis kernel for this
regressor = SVR(kernel = "rbf")
regressor.fit(x,y)

/home/amber/Desktop/Amber_Gautam/datascience/venv/lib/python3.6/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [27]:
# How to reverse the  scaling of your prediction 
# We need to do inverse transformation

In [46]:
# apply scaling on this
# scale on the same scale like earlier
# reverse the scaling of y because this will giv e me exact value like original salary
sc_y.inverse_transform(regressor.predict(sc_x.transform([[6.5]])))

array([252789.13921624])