##### K nearest neighbour (K-NN)
1. Put a new data point in defined classifier
2. Example: put point x in category1 or category2 classifier.
3. KNN is used to identify to decide this.
4. Build a step by step guide

##### Steps for algorithms:
1. Choose the number k of neighbors (common or default value is 5)
2. Take the K neighbors to the new data point, according to Euclidean distance or also other distances (manhetten etc)
3. Among these K neighbors, count the number of data point in each category.
4. Assign the new data point to the category where you counted the most neignbors
5. Your model is ready
6. Now count the most nearest neighbour in both category and assign to them

In [1]:
# Import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# iloc, locate indexes
dataset = pd.read_csv('Social_Network_Ads.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [3]:
from sklearn.model_selection import train_test_split
# create 4 seperate set
# 1. X train: matrix of feature of training set
# 2. X test: matrix of feature of test set
# 3. Y train: matrix of independent variable of train set 
# 4. Y Test: matrix of independent variable of test set
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 1)

In [4]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [5]:
x_train

array([[-1.68062015e+00, -5.92416706e-01],
       [ 8.69241193e-01,  5.63566526e-01],
       [-6.01832657e-01, -1.03702564e+00],
       [ 9.67312783e-01, -1.15558802e+00],
       [-2.09546297e-01, -5.62776110e-01],
       [ 1.82740063e-01,  8.00691292e-01],
       [-4.05689477e-01,  1.30458142e+00],
       [ 1.16345596e+00,  5.04285335e-01],
       [ 7.71169603e-01,  2.96801165e-01],
       [ 6.73098013e-01, -8.88822663e-01],
       [ 3.78883243e-01, -2.96010749e-01],
       [ 4.76954833e-01, -4.73854323e-01],
       [-2.09546297e-01,  1.18957591e-01],
       [ 3.78883243e-01,  8.93169951e-02],
       [-9.94119017e-01,  8.00691292e-01],
       [-6.99904247e-01,  1.39350321e+00],
       [ 3.78883243e-01, -5.03494919e-01],
       [ 3.78883243e-01, -5.03494919e-01],
       [-1.68062015e+00,  3.85722952e-01],
       [ 8.69241193e-01, -8.29541472e-01],
       [-9.94119017e-01, -1.12594743e+00],
       [-2.09546297e-01,  5.96763994e-02],
       [ 1.16345596e+00, -1.21486922e+00],
       [-2.

In [6]:
x_test

array([[-0.11147471, -1.06666624],
       [ 0.18274006, -0.23672956],
       [-0.11147471,  1.4527844 ],
       [ 0.18274006,  1.57134678],
       [-1.09219061,  1.4527844 ],
       [ 0.08466847, -0.11816717],
       [-1.68062015, -0.97774445],
       [ 1.16345596,  0.59320712],
       [-0.60183266, -1.51127517],
       [ 1.06538437,  2.1345181 ],
       [-0.30761789,  0.089317  ],
       [ 0.18274006,  0.11895759],
       [-0.2095463 ,  0.089317  ],
       [ 1.06538437,  1.83811214],
       [ 1.55574232,  0.38572295],
       [ 1.84995709,  1.89739333],
       [ 2.24224345,  0.41536355],
       [-0.99411902, -0.32565134],
       [-0.89604743,  0.53392593],
       [ 2.24224345,  0.97853487],
       [ 0.28081165,  0.17823878],
       [ 1.26152755,  0.56356653],
       [ 0.67309801,  2.07523691],
       [ 0.96731278, -0.77026028],
       [ 0.7711696 , -1.27415041],
       [-1.09219061, -1.60019696],
       [ 2.04610027, -0.6516979 ],
       [ 1.16345596,  0.14859819],
       [ 1.55574232,

In [24]:
# Training the KNN model on training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, p=2, metric="minkowski")
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [28]:
# predicting new result
classifier.predict(sc.transform([[30,87000]]))

array([0])

In [29]:
# predicting test result
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]]


In [30]:
# confusion metrics
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[50  8]
 [ 4 38]]


0.88