##### Logistic regressionL Based on sigmoid function
1. The point in logistic regression is find best fit line using the formula.
2. What can we use in logistic regression (predicting  Probability (0 and 1))
3. How to predict
4. Select the line (0.5) anything below the line is projected down and not going to consider
5. Select line (0.5) anything above  the line is projected above and going to take consider.

##### Steps to perform
1. Import libraries
2. Import the dataset
3. Split the dataset into Test and Training dataset
4. Feature scaling
5. Training the logistic regression
6. Predicting a new result
7. Predicting the test result
8. Making the confusion marix
9. Visualize the training set result
10. Visualize the test set result

##### Confusion Matrix: 
* In the field of machine learning and specifically the problem of statistical classification, a confusion matrix, also known as an error matrix. A confusion matrix is a table that is often used to describe the performance of a classification model (or “classifier”) on a set of test data for which the true values are known
* A confusion matrix is a summary of prediction results on a classification problem. The number of correct and incorrect predictions are summarized with count values and broken down by each class. This is the key to the confusion matrix. The confusion matrix shows the ways in which your classification model is confused when it makes predictions. 

In [1]:
# Import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# iloc, locate indexes
dataset = pd.read_csv('Social_Network_Ads.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [6]:
from sklearn.model_selection import train_test_split
# create 4 seperate set
# 1. X train: matrix of feature of training set
# 2. X test: matrix of feature of test set
# 3. Y train: matrix of independent variable of train set 
# 4. Y Test: matrix of independent variable of test set
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 1)

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
# Feature scaling
# why need to apply for feature scaling not necessary in logisitic regression
# still applying it to increase performance

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [12]:
x_train

array([[-1.68062015e+00, -5.92416706e-01],
       [ 8.69241193e-01,  5.63566526e-01],
       [-6.01832657e-01, -1.03702564e+00],
       [ 9.67312783e-01, -1.15558802e+00],
       [-2.09546297e-01, -5.62776110e-01],
       [ 1.82740063e-01,  8.00691292e-01],
       [-4.05689477e-01,  1.30458142e+00],
       [ 1.16345596e+00,  5.04285335e-01],
       [ 7.71169603e-01,  2.96801165e-01],
       [ 6.73098013e-01, -8.88822663e-01],
       [ 3.78883243e-01, -2.96010749e-01],
       [ 4.76954833e-01, -4.73854323e-01],
       [-2.09546297e-01,  1.18957591e-01],
       [ 3.78883243e-01,  8.93169951e-02],
       [-9.94119017e-01,  8.00691292e-01],
       [-6.99904247e-01,  1.39350321e+00],
       [ 3.78883243e-01, -5.03494919e-01],
       [ 3.78883243e-01, -5.03494919e-01],
       [-1.68062015e+00,  3.85722952e-01],
       [ 8.69241193e-01, -8.29541472e-01],
       [-9.94119017e-01, -1.12594743e+00],
       [-2.09546297e-01,  5.96763994e-02],
       [ 1.16345596e+00, -1.21486922e+00],
       [-2.

In [13]:
x_test

array([[-2.89053269e-01, -1.11810479e+00],
       [-1.89100270e-02, -3.15568669e-01],
       [-2.89053269e-01,  1.31816558e+00],
       [-1.89100270e-02,  1.43281360e+00],
       [-1.18953074e+00,  1.31816558e+00],
       [-1.08957774e-01, -2.00920651e-01],
       [-1.72981723e+00, -1.03211878e+00],
       [ 8.81567447e-01,  4.86967455e-01],
       [-7.39292006e-01, -1.54803486e+00],
       [ 7.91519700e-01,  1.97739168e+00],
       [-4.69148764e-01, -2.86620044e-04],
       [-1.89100270e-02,  2.83753844e-02],
       [-3.79101017e-01, -2.86620044e-04],
       [ 7.91519700e-01,  1.69077164e+00],
       [ 1.24175844e+00,  2.86333424e-01],
       [ 1.51190168e+00,  1.74809565e+00],
       [ 1.87209267e+00,  3.14995428e-01],
       [-1.09948300e+00, -4.01554682e-01],
       [-1.00943525e+00,  4.29643446e-01],
       [ 1.87209267e+00,  8.59573512e-01],
       [ 7.11377205e-02,  8.56993932e-02],
       [ 9.71615195e-01,  4.58305450e-01],
       [ 4.31328710e-01,  1.92006768e+00],
       [ 7.

In [14]:
y_train

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0])

In [15]:
y_test

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0])

In [24]:
# Train the logistic model on the Training data set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)
# c in result is "c:1.0" inverse of regularization, small c high regularization, prevent from overfitting.

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
# How to tune your model to choose best parameters
# for predict, take 2 parameter as per this above dataset, age and salary and predict the purchased yes or no

In [31]:
# add transform method to scale, format 2D Array
print(classifier.predict(sc.transform([[31, 87000]])))

[0]


In [39]:
# Predict the test result
y_pred = classifier.predict(x_test)
np.set_printoptions(precision=2)
# this will show the result of y_test in one column and y_pred in one column
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1)

array([[0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0,

In [49]:
# Making of confusion matrix
# It shows the number of correct prediction and number of incorrect predictions
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[52  6]
 [16 26]]


0.78

In [51]:
# Visualize the Training set result:
# For visualize the training set we have 2d graph one shows age and one salary
# the customer is visualize in dot and a line in divide in 2 regions (yes or no) or (0 or 1). 
# A curve is seperated these two and a customer lies in one of these curve.
# The code is pretty advance: Not implement most of the time.
# For this curve we need two feature but in real scenario we have many feature.
